### ISSUE TITLE
I sent request to access pre-trained model, please accept it.

### ISSUE THREAD

**Issue by manvirvirk** [ncarraz/ESRGANplus#1]

**Comment by ncarraz** [comment]
I have updated the link so that requests are not needed to access the models.

**Comment by manvirvirk** [comment]
I have clicked on that link , still it needs permission to access pre trained model. 

Tarundeep Singh Virk

**Comment by ncarraz** [comment]
This is the link I updated: https://drive.google.com/drive/folders/1lNky9afqEP-qdxrAwDFPJ1g0ui4x7Sin

**Comment by manvirvirk** [comment]
could access now, thanks
