### ISSUE TITLE
Is the last_D.pth in google drive is ESRGAN+ path file?

### ISSUE THREAD

**Issue by cyun-404** [ncarraz/ESRGANplus#10]
I want to get ESRGAN+ test parh file. Is the last_D.pth in google drive is ESRGAN+ path file?
Can I get ESRGAN+ test parh file?

**Comment by ncarraz** [comment]
This might be what you are looking for : https://drive.google.com/file/d/1eUgUPQc5ifS1BmEngh1EZzR4Z7fLYejf/view?usp=sharing
