### ISSUE TITLE
I m having only LR images , do it require both LR and HR image pair?

### ISSUE THREAD

**Issue by manvirvirk** [ncarraz/ESRGANplus#2]

**Comment by ncarraz** [comment]
If you train the model, you need both HR and LR. However, if you just want to test, only LR images are required.

**Comment by manvirvirk** [comment]
for testing i m using only LR images and changes the path in required json file also but it is showing error that HR path is empty

**Comment by manvirvirk** [comment]
whole traceback is :

Traceback (most recent call last):
  File "test.py", line 28, in <module>
    test_set = create_dataset(dataset_opt)
  File "D:\ESRGANplus-master\codes\data\__init__.py", line 33, in create_dataset
    dataset = D(dataset_opt)
  File "D:\ESRGANplus-master\codes\data\LRHR_dataset.py", line 36, in __init__
    assert self.paths_HR, 'Error: HR path is empty.'
AssertionError: Error: HR path is empty.

**Comment by ncarraz** [comment]
You are right. This test is for evaluating the model so both HR and LR images are required. I will update the repository so that testing actually perform the super-resolution of only LR images.

**Comment by manvirvirk** [comment]
ok thanks (y) and it requires RRDB_SRGAN*4.pth file as well

**Comment by ncarraz** [comment]
Try it with the new code

**Comment by manvirvirk** [comment]
yes its working now. thanks (y)
