### ISSUE TITLE
Train on my own x2 dataset

### ISSUE THREAD

**Issue by ofir-dl** [ncarraz/ESRGANplus#3]
Hi,

I have a dataset of 512x512 LR images and corresponding 1024x1024 HR images.
I noticed that the pretrained networks (and the paper) deals with x4 super resolution.
How do you suggest using your code and pretrained networks in my case?

Thanks,
Ofir

**Comment by ncarraz** [comment]
If you want to use the pretrained models to super resolve the images, you only need the LR images. The resulting images will be 2048x2048. However, if you want to train using your own images, you either have to downgrade the HR images using x4 scale performing transfer learning on the pretrained models or train new models using x2 scale factor.

**Comment by ofir-dl** [comment]
I guess I'll train new models using x2 scale factor.
Do you mean that I should just change the "scale" parameter from 4 to 2 in 'train_ESRGANplus.json' (for example)

**Comment by ofir-dl** [comment]
I'm sorry:
I meant the 'upscale' argument of RRDBNet __init__() in architecture.py - should i just change it to 2 instead of 4?

**Comment by ncarraz** [comment]
Yes but you shoud change the "scale" to 2 in the json file ESRGANplus/codes/options/train/train_ESRGANplus.json
