### ISSUE TITLE
Run on multiple gpus

### ISSUE THREAD

**Issue by ofir-dl** [ncarraz/ESRGANplus#4]
Hi,

I'm trying to train on multiple GPUs.
However, changing the gpus_ids field in the training json file results in runtime Error:

**RuntimeError: expected device cuda:0 but got device cuda:1**

How do you suggest doing it?

Thanks,
Ofir

**Comment by ncarraz** [comment]
I have not adapted the code to run on mutiple GPUs yet. You should look at this https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html
