### ISSUE TITLE
Injecting Random Noise

### ISSUE THREAD

**Issue by seungjunlee96** [ncarraz/ESRGANplus#5]
Hi, 

Thank you for sharing your great work.

I tried to find the code for the noise injection layer of  nESRGAN+, but I was not able to.

Can you help me which code specifies the noise injection layer? 

Best,

Lee.

**Comment by ncarraz** [comment]
Hi,
I assume you did find the code. It is in the ESRGANplus/codes/models/modules/block.py file. The noise injection is defined in line 110 and used in line 243.
Best,
