### ISSUE TITLE
Could you check how to train for X8?

### ISSUE THREAD

**Issue by star4s** [ncarraz/ESRGANplus#7]
I am trying trainging X8.
I already check to run train X2 and X4 well.
When I modifed "scale": 8 at "train_ESRGANplus.json", the val_images result of my trainging for X8 was so bad.
My  train_ESRGANplus.json is :

{
    "name": "nESRGANplus_x8",
    "use_tb_logger": true,
    "model": "srragan",
    "scale": 8,
    "gpu_ids": [
        0
    ],
    "datasets": {
        "train": {
            "name": "DIV2K",
            "mode": "LRHR",
            "dataroot_HR": "./ESRGANplus/HR_train/",
            "dataroot_LR": "./ESRGANplus/LR_train/x8/",
            "subset_file": null,
            "use_shuffle": true,
            "n_workers": 8,
            "batch_size":16,
            "HR_size": 128,
            "use_flip": true,
            "use_rot": true
        },
        "val": {
            "name": "val_set14_part",
            "mode": "LRHR",
            "dataroot_HR": ./ESRGANplus/HR_val/",
            "dataroot_LR": ./ESRGANplus/LR_val/x8/"
        }
    },
    "path": {
        "root": "./ESRGANplus",
        "resume_state": null,
        "pretrain_model_G": null
    },
    "network_G": {
        "which_model_G": "RRDB_net",
        "norm_type": null,
        "mode": "CNA",
        "nf": 64,
        "nb": 23,
        "in_nc": 3,
        "out_nc": 3,
        "gc": 32,
        "group": 1
    },
    "network_D": {
        "which_model_D": "discriminator_vgg_128",
        "norm_type": "batch",
        "act_type": "leakyrelu",
        "mode": "CNA",
        "nf": 64,
        "in_nc": 3
    },
    "train": {
        "lr_G": 0.0001,
        "weight_decay_G": 0,
        "beta1_G": 0.9,
        "lr_D": 0.0001,
        "weight_decay_D": 0,
        "beta1_D": 0.9,
        "lr_scheme": "MultiStepLR",
        "lr_steps": [
            50000,
            100000,
            200000,
            300000
        ],
        "lr_gamma": 0.5,
        "pixel_criterion": "l1",
        "pixel_weight": 0.01,
        "feature_criterion": "l1",
        "feature_weight": 1,
        "gan_type": "vanilla",
        "gan_weight": 0.005,
        "manual_seed": 0,
        "niter": 500000.0,
        "val_freq": 500.0
    },
    "logger": {
        "print_freq": 50,
        "save_checkpoint_freq": 500.0
    }
}

Could you check how to train for X8?
Thank you for your attention.

**Comment by ncarraz** [comment]
All images for the experimentation were downsampled using a scaling factor of x4. The models were trained on those images using scale x4. If you wish to train using x8, you have to first downsample the images with that scale before training.

**Comment by star4s** [comment]
I got it. Thank you for your quick answer.
