### ISSUE TITLE
No codes about perceptual index in metrics directory

### ISSUE THREAD

**Issue by ChandlerHarden** [ncarraz/ESRGANplus#9]
Hello, I notice that your paper provides only 2 metrics: PSNR and perceptual index. But why do your programs use PSNR and SSIM as the metrics?  Could you please upload the perceptual index methods in your metrics directory?

**Comment by ncarraz** [comment]
Hi, you can find the code to compute the perceptual inde here https://github.com/roimehrez/PIRM2018 
It is preferable to use this official code for fair comparison with previous models
